version: '2.4'
services:
  app:
    container_name: ducksmanager-app
    image: ghcr.io/bperel/ducksmanager-app
    depends_on:
      - api
    restart: always
    networks:
      - public-network
      - dm2-network

  api:
    container_name: ducksmanager-api
    image: ghcr.io/bperel/ducksmanager-api
    restart: always
    networks:
      - public-network
      - dm2-network
      - dm-server_db-network
      - dm-server_cover-id-network

  coa-updater:
    container_name: coa-updater
    image: bperel/coa-updater
    #depends_on:
    #  - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: coa
      MYSQL_DATABASE_NEW: coa_new
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dm-server_db-network

  cover-updater:
    container_name: cover-updater
    restart: always
    image: bperel/duck-cover-id-updater
    # depends_on:
    #   - db
    environment:
      MYSQL_COVER_INFO_HOST: db
      MYSQL_COVER_INFO_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COVER_INFO_DATABASE: cover_info
      MYSQL_COA_HOST: db
      MYSQL_COA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COA_DATABASE: coa
      PASTEC_HOST: pastec
      PASTEC_PORT: 4212
      PASTEC_CONTAINER_HOME: /pastec/build
    networks:
      - dm-server_db-network
      - dm-server_cover-id-network

  stats-updater:
    container_name: stats-updater
    image: bperel/dm-stats-updater
    # depends_on:
    #   - db
    environment:
      MYSQL_COA_HOST: db
      MYSQL_COA_DATABASE: coa
      MYSQL_DM_STATS_HOST: db
      MYSQL_DM_STATS_DATABASE: dm_stats
      MYSQL_DM_HOST: db
      MYSQL_DM_DATABASE: dm
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dm-server_db-network

  sprite-names-updater:
    container_name: sprite-names-updater
    image: bash
    # depends_on:
    #   - db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysql -uroot -p${MYSQL_ROOT_PASSWORD} dm -e "CALL generate_sprite_names"
    networks:
      - dm-server_db-network

  duck-estimator:
    container_name: duck-estimator
    image: mcr.microsoft.com/playwright:focal
    # depends_on:
    #   - db
    environment:
      MYSQL_COA_HOST: db
      MYSQL_COA_PORT: 3306
      MYSQL_COA_DATABASE: coa
      MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      GIT_AUTHOR_NAME: Admin
      GIT_COMMITTER_NAME: Admin
      GIT_AUTHOR_EMAIL: admin@ducksmanager.net
      GIT_COMMITTER_EMAIL: admin@ducksmanager.net
    networks:
      - dm-server_db-network
    volumes:
      - dm-server_duck_estimator_cache: /home/cache
      - dm-server_node_cache: /root/.cache
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    command: bash -c " git clone --depth 1 --single-branch https://github.com/bperel/duck-estimator; cd duck-estimator; npm install; node duck-estimator.js --cache-dir=/home/cache; "

  sentry-relay:
    image: getsentry/relay
    restart: always
    container_name: sentry2
    volumes:
      - ./config/sentry-relay:/work/.relay
    networks:
      - public-network

networks:
  dm2-network:
  public-network:
    external: true
  dm-server_db-network:
    external: true
  dm-server_cover-id-network:
    external: true

volumes:
  dm-server_duck_estimator_cache:
