version: '3.8'
services:
  web:
    container_name: ducksmanager-web
    image: ghcr.io/bperel/ducksmanager-web
    depends_on:
      - api
    restart: always
    networks:
      - public-network
      - dm2-network

  web-websocket:
    container_name: ducksmanager-web-websocket
    image: ghcr.io/bperel/ducksmanager-web:websocket
    depends_on:
      - api-websocket
    restart: always
    networks:
      - public-network
      - dm2-network

  api:
    container_name: ducksmanager-api
    image: ghcr.io/bperel/ducksmanager-api
    restart: always
    networks:
      - public-network
      - dm2-network
      - dm-server_db-network
      - dm-server_cover-id-network

  api-websocket:
    container_name: ducksmanager-api-websocket
    image: ghcr.io/bperel/ducksmanager-api:websocket
    restart: always
    networks:
      - public-network
      - dm2-network
      - dm-server_db-network
      - dm-server_cover-id-network

  cover-updater:
    container_name: cover-updater
    image: bperel/duck-cover-id-updater
    # depends_on:
    #   - db
    environment:
      MYSQL_COVER_INFO_HOST: db
      MYSQL_COVER_INFO_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COVER_INFO_DATABASE: cover_info
      MYSQL_COA_HOST: db
      MYSQL_COA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COA_DATABASE: coa
      PASTEC_HOST: pastec
      PASTEC_PORT: 4212
      PASTEC_CONTAINER_HOME: /pastec/build
    networks:
      - dm-server_db-network
      - dm-server_cover-id-network

  sprite-names-updater:
    container_name: sprite-names-updater
    image: mariadb:10.7
    # depends_on:
    #   - db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysql -uroot -p${MYSQL_ROOT_PASSWORD} dm -e "CALL generate_sprite_names"
    networks:
      - dm-server_db-network

  sentry-relay:
    image: getsentry/relay
    restart: always
    container_name: sentry2
    volumes:
      - ./config/sentry-relay:/work/.relay
    networks:
      - public-network

networks:
  dm2-network:
  public-network:
    external: true
  dm-server_db-network:
    external: true
  dm-server_cover-id-network:
    external: true
