version: '2.4'
services:
  app:
    container_name: ducksmanager-app
    image: ghcr.io/bperel/ducksmanager-app
    depends_on:
      - api
    restart: always
    networks:
      - public-network
      - dm2-network

  sentry-relay:
    image: getsentry/relay
    restart: always
    container_name: sentry2
    volumes:
      - ./config/sentry-relay:/work/.relay
    networks:
      - public-network

networks:
  dm2-network:
  public-network:
    external: true
