services:
  stats-updater:
    init: true
    image: ghcr.io/bperel/stats-updater
    env_file:
      - .env
    environment:
      - DATABASE_URL_DM_STATS=${DATABASE_URL_DM_STATS}_new
    networks:
      - dm-server_db-network
      - ducksmanager_dm-network
networks:
  ducksmanager_dm-network:
    external: true
  dm-server_db-network:
    external: true
