services:
  stats-updater:
    init: true
    image: ghcr.io/bperel/stats-updater
    env_file:
      - ../../packages/api/.env.prod.local
    environment:
      MYSQL_DM_STATS_DATABASE: dm_stats
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dm-server_db-network
      - ducksmanager_dm-network
networks:
  ducksmanager_dm-network:
    external: true
  dm-server_db-network:
    external: true