services:
  stats-updater:
    init: true
    image: ghcr.io/bperel/stats-updater
    env_file:
      - ../../packages/api/.env.prod.local
    environment:
      MYSQL_COA_HOST: db
      MYSQL_COA_DATABASE: coa
      MYSQL_DM_STATS_HOST: db
      MYSQL_DM_STATS_DATABASE: dm_stats
      MYSQL_DM_HOST: db
      MYSQL_DM_DATABASE: dm
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dm-server_db-network
networks:
  dm-server_db-network:
    external: true