version: '2.4'
services:
  api:
    container_name: ducksmanager-api
    image: ghcr.io/bperel/ducksmanager-api
    restart: always
    networks:
      - public-network
      - dm2-network
      - dm-server_db-network
      - dm-server_cover-id-network

networks:
  dm2-network:
  public-network:
    external: true
  dm-server_db-network:
    external: true
  dm-server_cover-id-network:
    external: true
