version: "3.2"

services:
  edges:
    image: "bperel/dm-edges"
    container_name: edges
    restart: always
    env_file:
      - .env.prod.local
    working_dir: /usr/share/nginx/html
    volumes:
      - "../../edges:/usr/share/nginx/html/edges"
    networks:
      - public-network

networks:
  public-network:
    external: true
