services:
  edges:
    build:
      context: .
    container_name: edges
    restart: always
    env_file:
      - .env
    ports:
      - 8080:80
    working_dir: /usr/share/nginx/html
    volumes:
      - "./edges:/usr/share/nginx/html/edges"
