version: '3.2'

services:
  edges:
    image: "nginx"
    container_name: edges
    restart: always
    volumes:
      - "./edges:/usr/share/nginx/html/edges"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - ./template-variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
    env_file:
      - .env.prod.local
    networks:
      - public-network

networks:
  public-network:
    external: true