name: certificate-renewer

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  renew-certificates:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Renew certificates
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN_DM }}
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          command_timeout: 2m
          envs: DOCKER_REGISTRY_TOKEN_DM
          script: |
            cd workspace
            docker compose run --rm certbot && docker compose up -d --force-recreate web_global
