name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "test-monorepo-build"
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "${GITHUB_REF#refs/heads/}"
        #   fallback-sha: "ffffff"

      - run: |
          echo "HEAD: ${{ env.NX_HEAD }}"
          echo "BASE: ${{ env.NX_BASE }}"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - uses: oven-sh/setup-bun@v1

      - name: Check apps changed since the last successful commit
        run: |
          changedApps=$(pnpm -r $changedAppsCommitFilter -F './apps/**' ls --depth -1 -j)
          echo "Changed apps: $changedApps"

      - name: Install dependencies
        run: |
          set -x
          pnpm -r $changedAppsCommitFilter -F './apps/**' install

      - name: Build apps
        run: |
          pnpm -r $changedAppsCommitFilter -F './apps/**' build
          exit 1
