name: deploy-ducksmanager

on:
  workflow_dispatch:
  push:
    branches:
      - 'symfony-to-vite'
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Download .env file
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          fingerprint: ${{ secrets.PRODUCTION_SSH_FINGERPRINT }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: /home/bperel/workspace/DucksManager2/.env.prod.local
          target: .env.prod.local

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: bperel
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN_DM }}

      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/x86_64
          push: true
          target: app
          tags: |
            ghcr.io/bperel/ducksmanager-app:latest

      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/x86_64
          push: true
          target: api
          tags: |
            ghcr.io/bperel/ducksmanager-api:latest

      - name: Upload docker-compose.yml file
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          fingerprint: ${{ secrets.PRODUCTION_SSH_FINGERPRINT }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: docker-compose.yml
          target: /home/bperel/workspace/DucksManager2/docker-compose.yml

      - name: Recreate container
        uses: appleboy/ssh-action@v0.1.4
        env:
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN_DM }}
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          command_timeout: 2m
          envs: DOCKER_REGISTRY_TOKEN_DM
          script: |
            cd workspace/DucksManager2
            echo $DOCKER_REGISTRY_TOKEN | docker login ghcr.io -u bperel --password-stdin
            docker compose pull && docker compose up -d --force-recreate
