name: deploy-edgecreator

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: oven-sh/setup-bun@v1
      - name: Check out repository
        uses: actions/checkout@master

      - name: Download .env file
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          fingerprint: ${{ secrets.PRODUCTION_SSH_FINGERPRINT }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: /home/bperel/workspace/EdgeCreator2/.env.prod
          target: apps/edgecreator/.env.prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: bperel
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN_DM }}

      - name: Build and push app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/edgecreator/Dockerfile
          platforms: linux/x86_64
          push: true
          target: app
          cache-from: type=registry,ref=ghcr.io/bperel/edgecreator-app:buildcache
          cache-to: type=registry,ref=ghcr.io/bperel/edgecreator-app:buildcache,mode=max
          tags: |
            ghcr.io/bperel/edgecreator-app:latest

      - name: Build and push api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/edgecreator/Dockerfile
          platforms: linux/x86_64
          push: true
          target: api
          cache-from: type=registry,ref=ghcr.io/bperel/edgecreator-api:buildcache
          cache-to: type=registry,ref=ghcr.io/bperel/edgecreator-api:buildcache,mode=max
          tags: |
            ghcr.io/bperel/edgecreator-api:latest

      - name: Upload docker-compose.yml config
        uses: nicklasfrahm/scp-action@v1.0.1
        with:
          direction: upload
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          fingerprint: ${{ secrets.PRODUCTION_SSH_FINGERPRINT }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: docker-compose.yml
          target: /home/bperel/workspace/EdgeCreator2/docker-compose.yml

      - name: Upload Sentry config
        uses: nicklasfrahm/scp-action@v1.0.1
        with:
          direction: upload
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          fingerprint: ${{ secrets.PRODUCTION_SSH_FINGERPRINT }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: config/sentry-relay/config.yml
          target: /home/bperel/workspace/EdgeCreator2/config/sentry-relay/config.yml

      - name: Upload Sentry project config
        uses: nicklasfrahm/scp-action@v1.0.1
        with:
          direction: upload
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          fingerprint: ${{ secrets.PRODUCTION_SSH_FINGERPRINT }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: config/sentry-relay/projects/5595460.json
          target: /home/bperel/workspace/EdgeCreator2/config/sentry-relay/projects/5595460.json

      - name: Recreate container
        uses: appleboy/ssh-action@v0.1.7
        env:
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN_DM }}
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          command_timeout: 2m
          envs: DOCKER_REGISTRY_TOKEN
          script: |
            cd workspace/EdgeCreator2
            echo $DOCKER_REGISTRY_TOKEN | docker login ghcr.io -u bperel --password-stdin
            docker compose pull && docker compose up -d --force-recreate
