version: '2'
services:
  edges:
    container_name: edges
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ${EDGES_PATH}:/usr/share/nginx/html/edges
      - ./nginx_edges.local.conf:/etc/nginx/conf.d/default.conf
    restart: always
