version: "2.4"
services:
  app:
    container_name: edgecreator-app
    image: ghcr.io/bperel/edgecreator-app
    depends_on:
      - api
    restart: always
    networks:
      - public-network
      - ec2-network

  app-websocket:
    container_name: edgecreator-app-websocket
    image: ghcr.io/bperel/edgecreator-app:websocket
    depends_on:
      - api
    restart: always
    networks:
      - public-network
      - ec2-network

  sentry-relay:
    image: getsentry/relay
    restart: always
    container_name: sentry-edgecreator
    volumes:
      - ./config/sentry-relay:/work/.relay
    networks:
      - public-network

networks:
  ec2-network:
  public-network:
    external: true
